#数据库配置
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/true?useUnicode=false&characterEncoding=utf-8&allowMultiQueries=true;useAffectedRows=true
  username: root
  password: root
spring:
  rabbitmq:
    host: 120.26.231.118
    port: 5672
    username: guest
    password: xuexin_guest_2017